apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kuard
  name: kuard
  namespace: default
spec:
  replicas: 3 
  selector:
    matchLabels:
      run: kuard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:green
        name: kuard
        resources: {}
      terminationGracePeriodSeconds: 30
