apiVersion: v1
kind: Service
metadata:
  labels:
    run: kuard
  name: kuard
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: kuard
  sessionAffinity: None
  type: LoadBalancer 
