apiVersion: v1
kind: Pod
metadata:
  name: NAME 
  namespace: default
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:green
    name: kuard
    resources:
      requests:
        cpu: 1.0
        memory: 100M
      limits:
        cpu: 1.0 
        memory: 100M
